[package]
org = "vikum"
name = "payment_service"
version = "0.1.0"
distribution = "2201.13.1"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "com.h2database"
artifactId = "h2"
version = "2.2.224"
